### ISSUE TITLE
同学，有课程ppt吗？有偿求

### ISSUE THREAD

**Issue by woodenGuo** [JINGE-ui/PrinciplesOfComputerOrganization#1]

**Comment by JINGE-ui** [comment]
课程配套视频在中国大学MOOC：计算机组成原理（华中科技大学），实验资源及配套视频在MOOC：计算机硬件系统设计（华中科技大学）。我这只有课程的PPT，发一下邮箱号吧。

**Comment by woodenGuo** [comment]
> 课程配套视频在中国大学MOOC：计算机组成原理（华中科技大学），实验资源及配套视频在MOOC：计算机硬件系统设计（华中科技大学）。我这只有课程的PPT，发一下邮箱号吧。

**Comment by woodenGuo** [comment]
> 课程配套视频在中国大学MOOC：计算机组成原理（华中科技大学），实验资源及配套视频在MOOC：计算机硬件系统设计（华中科技大学）。我这只有课程的PPT，发一下邮箱号吧。

**Comment by woodenGuo** [comment]
> 课程配套视频在中国大学MOOC：计算机组成原理（华中科技大学），实验资源及配套视频在MOOC：计算机硬件系统设计（华中科技大学）。我这只有课程的PPT，发一下邮箱号吧。

woodenguo@sanxiau.edu.cn，非常3q!
